"""Update user model and schema

Revision ID: 9fdd098bb391
Revises: ace88ac257c6
Create Date: 2024-02-25 08:54:05.168658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fdd098bb391'
down_revision: Union[str, None] = 'ace88ac257c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(length=225), nullable=True))
    op.add_column('users', sa.Column('access_token', sa.String(length=225), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_token')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
