"""add otp model

Revision ID: daab2f395e1e
Revises: 544d9d1c80d3
Create Date: 2024-03-12 07:52:02.483450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daab2f395e1e'
down_revision: Union[str, None] = '544d9d1c80d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'otps',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(225), nullable=False),
        sa.Column('token', sa.String(6), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True),nullable=False),
        sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otps')
    # ### end Alembic commands ###
