name: vlecture deploy to railway

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Railway
      run: npm i -g @railway/cli

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        railway run --service ${{ secrets.RAILWAY_SERVICE }} python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    - name: Run pytest
      run: |
        pytest tests
      env:
        DB_URL: ${{ secrets.DB_URL }}
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    - name: Deploy
      run: railway up --service ${{ secrets.RAILWAY_SERVICE }}
      env: 
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

# Reference: https://github.com/bervProject/MyPersonalWebAPI/blob/main/.github/workflows/node%26docker.yml